import type { User, Entity, Client, DictItem, Holiday, Rfq, BomNode, Template, Offer, OfferLine } from '@/types/models';

export {
  seedCascadeSuppliers,
  seedCascadeSuppliers as seedSuppliers,
  seedComponentGroups,
  seedComponentKinds,
  seedOperations,
  seedComponentKindSuppliers,
} from './seedCascade';

export const seedUsers: User[] = [
  {
    id: 1,
    email: 'admin@aero.pl',
    firstName: 'Admin',
    lastName: 'Systemowy',
    phone: '+48123456789',
    role: 'SUPER_ADMIN',
    active: true,
  },
  {
    id: 2,
    email: 'katarzyna@aero.pl',
    firstName: 'Katarzyna',
    lastName: 'Kierownik',
    phone: '+48234567890',
    role: 'KIEROWNIK',
    active: true,
  },
  {
    id: 3,
    email: 'piotr@aero.pl',
    firstName: 'Piotr',
    lastName: 'Pracownik',
    phone: '+48345678901',
    role: 'PRACOWNIK',
    active: true,
  },
];

export const seedEntities: Entity[] = [
  {
    id: 1,
    name: 'AERO Sp. z o.o.',
    nip: '1234567890',
    address: 'ul. Lotnicza 1, 00-000 Warszawa',
    active: true,
  },
  {
    id: 2,
    name: 'AERO Serwis JDG',
    nip: '0987654321',
    address: 'ul. Techniczna 5, 80-000 Gdańsk',
    active: true,
  },
];

export const seedClients: Client[] = [
  {
    id: 1,
    name: 'AIRBUS Defence and Space',
    nip: '1111111111',
    address: 'ul. Europejska 1, 00-950 Warszawa',
    contactPerson: 'Jan Kowalski',
    email: 'j.kowalski@airbus.com',
    phone: '+48500000001',
    active: true,
  },
  {
    id: 2,
    name: 'Bombardier Transportation',
    nip: '2222222222',
    address: 'ul. Portowa 10, 70-000 Szczecin',
    contactPerson: 'Maria Nowak',
    email: 'm.nowak@bombardier.com',
    phone: '+48500000002',
    active: true,
  },
  {
    id: 3,
    name: 'Siemens Mobility Polska',
    nip: '3333333333',
    address: 'ul. Przemysłowa 5, 40-000 Katowice',
    contactPerson: 'Andrzej Lewandowski',
    email: 'a.lewandowski@siemens.com',
    phone: '+48500000003',
    active: true,
  },
  {
    id: 4,
    name: 'CFM International',
    nip: '4444444444',
    address: 'ul. Technologiczna 8, 60-000 Poznań',
    contactPerson: 'Ewa Dąbrowska',
    email: 'e.dabrowska@cfm.com',
    phone: '+48500000004',
    active: true,
  },
  {
    id: 5,
    name: 'Safran Aerosystems',
    nip: '5555555555',
    address: 'ul. Lotnicza 15, 31-000 Kraków',
    contactPerson: 'Krzysztof Zieliński',
    email: 'k.zielinski@safran.com',
    phone: '+48500000005',
    active: true,
  },
  {
    id: 6,
    name: 'Magellan Aerospace',
    nip: '6666666666',
    address: 'ul. Fabryczna 2, 20-000 Lublin',
    contactPerson: 'Anna Wysocka',
    email: 'a.wysocka@magellan.com',
    phone: '+48500000006',
    active: true,
  },
];

export const seedInquiryTypes: DictItem[] = [
  { id: 1, code: 'STALE', labelPL: 'Stałe', sort: 1, active: true },
  { id: 2, code: 'PRODUKCJA', labelPL: 'Produkcja', sort: 2, active: true },
  { id: 3, code: 'HANDEL', labelPL: 'Handel', sort: 3, active: true },
  { id: 4, code: 'AEROPARTS', labelPL: 'AeroParts', sort: 4, active: true },
  { id: 5, code: 'PROJEKT', labelPL: 'Projekt', sort: 5, active: true },
];

export const seedMaterials: DictItem[] = [
  { id: 1, code: 'S355', labelPL: 'S355', sort: 1, active: true },
  { id: 2, code: '304L', labelPL: '304L', sort: 2, active: true },
  { id: 3, code: 'AL6061', labelPL: 'AL6061', sort: 3, active: true },
  { id: 4, code: 'C45', labelPL: 'C45', sort: 4, active: true },
  { id: 5, code: 'PA6', labelPL: 'PA6', sort: 5, active: true },
  { id: 6, code: 'MOSIADZ', labelPL: 'Mosiądz', sort: 6, active: true },
  { id: 7, code: 'TYTAN_GR5', labelPL: 'Tytan Gr5', sort: 7, active: true },
  { id: 8, code: 'INNE', labelPL: 'Inne', sort: 8, active: true },
];

export const seedCertificates: DictItem[] = [
  { id: 1, code: 'CMM', labelPL: 'CMM', sort: 1, active: true },
  { id: 2, code: '3.1', labelPL: '3.1', sort: 2, active: true },
  { id: 3, code: 'NADCAP', labelPL: 'NADCAP', sort: 3, active: true },
  { id: 4, code: 'ATEST_HUTNICZY', labelPL: 'Atest hutniczy', sort: 4, active: true },
];

export const seedDeliveryTimes: DictItem[] = [
  { id: 1, code: 'T1', labelPL: '1 tydzień', sort: 1, active: true },
  { id: 2, code: 'T2', labelPL: '2 tygodnie', sort: 2, active: true },
  { id: 3, code: 'T3', labelPL: '3 tygodnie', sort: 3, active: true },
  { id: 4, code: 'T4', labelPL: '4 tygodnie', sort: 4, active: true },
  { id: 5, code: 'T5', labelPL: '5 tygodni', sort: 5, active: true },
  { id: 6, code: 'T6', labelPL: '6 tygodni', sort: 6, active: true },
  { id: 7, code: 'T7', labelPL: '7 tygodni', sort: 7, active: true },
  { id: 8, code: 'T8', labelPL: '8 tygodni', sort: 8, active: true },
];

export const seedHolidays: Holiday[] = [
  { id: 1, date: '2026-01-01', name: 'Nowy Rok' },
  { id: 2, date: '2026-01-06', name: 'Trzech Króli' },
  { id: 3, date: '2026-04-06', name: 'Poniedziałek Wielkanocny' },
  { id: 4, date: '2026-05-01', name: 'Święto Pracy' },
  { id: 5, date: '2026-06-04', name: 'Boże Ciało' },
  { id: 6, date: '2026-08-15', name: 'Wniebowzięcie Najświętszej Maryi Panny' },
  { id: 7, date: '2026-11-11', name: 'Niepodległości' },
  { id: 8, date: '2026-12-25', name: 'Boże Narodzenie' },
];

export const seedRfqs: Rfq[] = [
  {
    id: 1,
    numer: '2150-05-2026',
    clientId: 1,
    entityId: 1,
    inquiryTypeId: 1,
    nazwa: 'Części do systemu klimatyzacji',
    opis: 'Zapytanie na części do systemu klimatyzacji dla samolotów.',
    status: 'WYSLANE',
    coordinatorId: 2,
    dataZapytania: '2026-05-10',
    deadline: '2026-05-24',
    dataWyslania: '2026-05-12',
    wymaganaDokumentacja: true,
    certificateIds: [1, 2],
    version: 1,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-12T11:00:00Z',
  },
  {
    id: 2,
    numer: '2151-05-2026',
    clientId: 2,
    entityId: 1,
    inquiryTypeId: 2,
    nazwa: 'Rury tytanowe',
    opis: 'Rury o specjalnym profilu z tytanu.',
    status: 'ZAAKCEPTOWANE',
    coordinatorId: 2,
    dataZapytania: '2026-05-15',
    deadline: '2026-05-29',
    dataWyslania: '2026-05-17',
    wymaganaDokumentacja: false,
    certificateIds: [3],
    version: 1,
    createdAt: '2026-05-15T09:30:00Z',
    updatedAt: '2026-05-17T14:00:00Z',
  },
  {
    id: 3,
    numer: '2152-05-2026',
    clientId: 3,
    entityId: 2,
    inquiryTypeId: 3,
    nazwa: 'Komponenty elektroniczne',
    opis: 'Różne komponenty elektroniczne.',
    status: 'NOWE',
    coordinatorId: 3,
    dataZapytania: '2026-05-20',
    deadline: '2026-06-03',
    dataWyslania: null,
    wymaganaDokumentacja: true,
    certificateIds: [2, 4],
    version: 1,
    createdAt: '2026-05-20T13:00:00Z',
    updatedAt: '2026-05-20T13:00:00Z',
  },
  {
    id: 4,
    numer: '2153-06-2026',
    clientId: 4,
    entityId: 1,
    inquiryTypeId: 1,
    nazwa: 'Silniki pneumatyczne',
    opis: 'Silniki pneumatyczne do systemów pomocniczych.',
    status: 'NOWE',
    coordinatorId: 2,
    dataZapytania: '2026-06-01',
    deadline: '2026-06-08',
    dataWyslania: null,
    wymaganaDokumentacja: false,
    certificateIds: [],
    version: 1,
    createdAt: '2026-06-01T08:00:00Z',
    updatedAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 5,
    numer: '2154-06-2026',
    clientId: 5,
    entityId: 1,
    inquiryTypeId: 4,
    nazwa: 'Łożyska precyzyjne',
    opis: 'Łożyska o wysokiej precyzji do systemów hydraulicznych.',
    status: 'WYSLANE',
    coordinatorId: 2,
    dataZapytania: '2026-06-05',
    deadline: '2026-06-19',
    dataWyslania: '2026-06-06',
    wymaganaDokumentacja: true,
    certificateIds: [1],
    version: 1,
    createdAt: '2026-06-05T11:30:00Z',
    updatedAt: '2026-06-06T09:00:00Z',
  },
  {
    id: 6,
    numer: '2155-06-2026',
    clientId: 6,
    entityId: 2,
    inquiryTypeId: 2,
    nazwa: 'Uszczelki specjalistyczne',
    opis: 'Uszczelki do systemów hydraulicznych.',
    status: 'WSTRZYMANE',
    coordinatorId: 3,
    dataZapytania: '2026-06-10',
    deadline: '2026-06-24',
    dataWyslania: null,
    wymaganaDokumentacja: false,
    certificateIds: [2],
    version: 1,
    createdAt: '2026-06-10T15:00:00Z',
    updatedAt: '2026-06-10T15:00:00Z',
  },
  {
    id: 7,
    numer: '2156-06-2026',
    clientId: 1,
    entityId: 1,
    inquiryTypeId: 3,
    nazwa: 'Radiatory aluminiowe',
    opis: 'Radiatory do systemów chłodzenia.',
    status: 'NOWE',
    coordinatorId: 2,
    dataZapytania: '2026-06-15',
    deadline: '2026-06-22',
    dataWyslania: null,
    wymaganaDokumentacja: true,
    certificateIds: [3],
    version: 1,
    createdAt: '2026-06-15T10:00:00Z',
    updatedAt: '2026-06-15T10:00:00Z',
  },
  {
    id: 8,
    numer: '2157-06-2026',
    clientId: 2,
    entityId: 1,
    inquiryTypeId: 5,
    nazwa: 'Wentylatory specjalistyczne',
    opis: 'Wentylatory do systemów zasilania powietrzem.',
    status: 'WYSLANE',
    coordinatorId: 2,
    dataZapytania: '2026-06-20',
    deadline: '2026-07-04',
    dataWyslania: '2026-06-22',
    wymaganaDokumentacja: false,
    certificateIds: [],
    version: 1,
    createdAt: '2026-06-20T14:00:00Z',
    updatedAt: '2026-06-22T16:00:00Z',
  },
  {
    id: 9,
    numer: '2158-07-2026',
    clientId: 3,
    entityId: 1,
    inquiryTypeId: 1,
    nazwa: 'Stół inspekcyjny',
    opis: 'Stół inspekcyjny dla laboratorium.',
    status: 'NOWE',
    coordinatorId: 2,
    dataZapytania: '2026-07-02',
    deadline: '2026-07-09',
    dataWyslania: null,
    wymaganaDokumentacja: true,
    certificateIds: [1, 2],
    version: 1,
    createdAt: '2026-07-02T09:00:00Z',
    updatedAt: '2026-07-02T09:00:00Z',
  },
  {
    id: 10,
    numer: '2159-07-2026',
    clientId: 4,
    entityId: 1,
    inquiryTypeId: 2,
    nazwa: 'Rama transportowa',
    opis: 'Rama do transportu komponentów.',
    status: 'NOWE',
    coordinatorId: 3,
    dataZapytania: '2026-07-05',
    deadline: '2026-07-19',
    dataWyslania: null,
    wymaganaDokumentacja: false,
    certificateIds: [],
    version: 1,
    createdAt: '2026-07-05T12:00:00Z',
    updatedAt: '2026-07-05T12:00:00Z',
  },
];

export const seedBomNodes: BomNode[] = [
  {
    id: 1,
    rfqId: 9,
    templateId: null,
    parentId: null,
    lp: 1,
    numerDetalu: 'ST-INS-2026-001',
    ilosc: 1,
    nazwaOpis: 'Stół inspekcyjny',
    groupId: 2,
    kindId: 23,
    operations: [{ operationId: 59, cena: 0, supplierId: null, supplierOffers: [] }],
    materialId: 1,
    materialWymiary: '2000x1000x800 mm',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [],
  },
  {
    id: 2,
    rfqId: 9,
    templateId: null,
    parentId: 1,
    lp: 1,
    numerDetalu: 'RAMA-001',
    ilosc: 1,
    nazwaOpis: 'Rama nośna',
    groupId: 2,
    kindId: 23,
    operations: [{ operationId: 59, cena: 0, supplierId: null, supplierOffers: [] }],
    materialId: 1,
    materialWymiary: '2000x1000 mm',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [],
  },
  {
    id: 3,
    rfqId: 9,
    templateId: null,
    parentId: 2,
    lp: 1,
    numerDetalu: 'BELKA-001',
    ilosc: 2,
    nazwaOpis: 'Belka poprzeczna',
    groupId: 2,
    kindId: 23,
    operations: [{ operationId: 59, cena: 0, supplierId: null, supplierOffers: [] }],
    materialId: 1,
    materialWymiary: '1000x50x50 mm',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [],
  },
  {
    id: 4,
    rfqId: 9,
    templateId: null,
    parentId: 3,
    lp: 1,
    numerDetalu: 'SRUBA-M8',
    ilosc: 16,
    nazwaOpis: 'Śruba M8',
    groupId: 3,
    kindId: 28,
    operations: [],
    materialId: 2,
    materialWymiary: 'M8x1.25x40',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [
      {
        id: 1,
        supplierId: 8,
        supplierName: 'OEM Technik',
        cena: 2.5,
        isFinal: false,
      },
      {
        id: 2,
        supplierId: 4,
        supplierName: 'Webus',
        cena: 2.2,
        isFinal: true,
      },
    ],
  },
  {
    id: 5,
    rfqId: 1,
    templateId: null,
    parentId: null,
    lp: 1,
    numerDetalu: 'KLIMA-2026-001',
    ilosc: 1,
    nazwaOpis: 'Zespół klimatyzacji',
    groupId: 2,
    kindId: 23,
    operations: [{ operationId: 59, cena: 0, supplierId: null, supplierOffers: [] }],
    materialId: null,
    materialWymiary: '',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [],
  },
  {
    id: 6,
    rfqId: 1,
    templateId: null,
    parentId: 5,
    lp: 1,
    numerDetalu: 'OBUD-WENT-001',
    ilosc: 1,
    nazwaOpis: 'Obudowa wentylatora',
    groupId: 2,
    kindId: 23,
    operations: [{ operationId: 59, cena: 0, supplierId: null, supplierOffers: [] }],
    materialId: 3,
    materialWymiary: '400x400x250 mm',
    procesySpecjalne: true,
    dodatkowe: 'Wycena ręczna działu produkcji',
    materialCost: 0,
    manualUnitCost: 500,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [],
  },
  {
    id: 7,
    rfqId: 1,
    templateId: null,
    parentId: 6,
    lp: 1,
    numerDetalu: 'BLACHA-AL-001',
    ilosc: 2,
    nazwaOpis: 'Blacha obudowy',
    groupId: 4,
    kindId: 48,
    operations: [],
    materialId: 3,
    materialWymiary: '400x400x2 mm',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [
      {
        id: 3,
        supplierId: 26,
        supplierName: 'Adamet',
        cena: 35,
        isFinal: true,
      },
    ],
  },
  {
    id: 8,
    rfqId: 1,
    templateId: null,
    parentId: 5,
    lp: 2,
    numerDetalu: 'FILTR-POW-001',
    ilosc: 2,
    nazwaOpis: 'Filtr powietrza',
    groupId: 3,
    kindId: 28,
    operations: [],
    materialId: 5,
    materialWymiary: '200x200x50 mm',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [
      {
        id: 4,
        supplierId: 8,
        supplierName: 'OEM Technik',
        cena: 52,
        isFinal: false,
      },
      {
        id: 5,
        supplierId: 4,
        supplierName: 'Webus',
        cena: 45,
        isFinal: true,
      },
    ],
  },
  {
    id: 9,
    rfqId: 5,
    templateId: null,
    parentId: null,
    lp: 1,
    numerDetalu: 'LOZ-ZESP-001',
    ilosc: 1,
    nazwaOpis: 'Zespół łożyskowy',
    groupId: 2,
    kindId: 23,
    operations: [{ operationId: 59, cena: 0, supplierId: null, supplierOffers: [] }],
    materialId: null,
    materialWymiary: '',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [],
  },
  {
    id: 10,
    rfqId: 5,
    templateId: null,
    parentId: 9,
    lp: 1,
    numerDetalu: 'LOZ-KUL-6205',
    ilosc: 8,
    nazwaOpis: 'Łożysko kulkowe 6205',
    groupId: 3,
    kindId: 28,
    operations: [],
    materialId: 4,
    materialWymiary: 'fi 25/52x15 mm',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [
      {
        id: 6,
        supplierId: 2,
        supplierName: 'Asmet',
        cena: 12.5,
        isFinal: true,
      },
      {
        id: 7,
        supplierId: 8,
        supplierName: 'OEM Technik',
        cena: 14,
        isFinal: false,
      },
    ],
  },
  {
    id: 11,
    rfqId: 5,
    templateId: null,
    parentId: 9,
    lp: 2,
    numerDetalu: 'PIER-DYST-001',
    ilosc: 4,
    nazwaOpis: 'Pierścień dystansowy',
    groupId: 1,
    kindId: 1,
    operations: [{ operationId: 1, cena: 0, supplierId: null, supplierOffers: [] }],
    materialId: 6,
    materialWymiary: 'fi 30/40x5 mm',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [
      {
        id: 8,
        supplierId: 15,
        supplierName: 'Moris',
        cena: 6,
        isFinal: true,
      },
    ],
  },
  {
    id: 12,
    rfqId: null,
    templateId: 1,
    parentId: null,
    lp: 1,
    numerDetalu: 'TPL-ST-INS-001',
    ilosc: 1,
    nazwaOpis: 'Stół inspekcyjny',
    groupId: 2,
    kindId: 23,
    operations: [{ operationId: 59, cena: 0, supplierId: null, supplierOffers: [] }],
    materialId: 1,
    materialWymiary: '2000x1000x800 mm',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [],
  },
  {
    id: 13,
    rfqId: null,
    templateId: 1,
    parentId: 12,
    lp: 1,
    numerDetalu: 'TPL-RAMA-001',
    ilosc: 1,
    nazwaOpis: 'Rama nośna',
    groupId: 2,
    kindId: 23,
    operations: [{ operationId: 59, cena: 0, supplierId: null, supplierOffers: [] }],
    materialId: 1,
    materialWymiary: '2000x1000 mm',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [],
  },
  {
    id: 14,
    rfqId: null,
    templateId: 1,
    parentId: 13,
    lp: 1,
    numerDetalu: 'TPL-SRUBA-M8',
    ilosc: 16,
    nazwaOpis: 'Śruba M8',
    groupId: 3,
    kindId: 28,
    operations: [],
    materialId: 2,
    materialWymiary: 'M8x1.25x40',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [
      {
        id: 9,
        supplierId: 4,
        supplierName: 'Webus',
        cena: 2.2,
        isFinal: true,
      },
    ],
  },
  {
    id: 15,
    rfqId: null,
    templateId: 2,
    parentId: null,
    lp: 1,
    numerDetalu: 'TPL-RAMA-TR-001',
    ilosc: 1,
    nazwaOpis: 'Rama transportowa',
    groupId: 2,
    kindId: 23,
    operations: [{ operationId: 59, cena: 0, supplierId: null, supplierOffers: [] }],
    materialId: 1,
    materialWymiary: '1500x800x600 mm',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [],
  },
  {
    id: 16,
    rfqId: null,
    templateId: 2,
    parentId: 15,
    lp: 1,
    numerDetalu: 'TPL-PROFIL-001',
    ilosc: 4,
    nazwaOpis: 'Profil stalowy 60x60',
    groupId: 4,
    kindId: 39,
    operations: [],
    materialId: 1,
    materialWymiary: '60x60x1500 mm',
    procesySpecjalne: false,
    dodatkowe: '',
    materialCost: 0,
    manualUnitCost: null,
    ownCost: 0,
    unitCost: 0,
    totalCost: 0,
    version: 1,
    supplierOffers: [
      {
        id: 10,
        supplierId: 15,
        supplierName: 'Moris',
        cena: 85,
        isFinal: true,
      },
    ],
  },
];

export const seedTemplates: Template[] = [
  {
    id: 1,
    name: 'Stół inspekcyjny',
    createdAt: '2026-06-15T10:00:00Z',
    updatedAt: '2026-06-15T10:00:00Z',
  },
  {
    id: 2,
    name: 'Rama transportowa',
    createdAt: '2026-06-20T14:00:00Z',
    updatedAt: '2026-06-20T14:00:00Z',
  },
];

export const seedOffers: Offer[] = [
  {
    id: 1,
    rfqId: 1,
    numer: '2150-05-2026',
    revision: 'A',
    entityId: 1,
    clientId: 1,
    nrZamowieniaKlienta: null,
    status: 'SZKIC',
    rabatType: null,
    rabatValue: null,
    salesRepId: 2,
    deliveryTimeId: 1,
    version: 1,
    createdAt: '2026-05-15T10:00:00Z',
    updatedAt: '2026-05-15T10:00:00Z',
  },
  {
    id: 2,
    rfqId: 2,
    numer: '2151-05-2026',
    revision: 'A',
    entityId: 1,
    clientId: 2,
    nrZamowieniaKlienta: null,
    status: 'WYSLANA',
    rabatType: null,
    rabatValue: null,
    salesRepId: 2,
    deliveryTimeId: 2,
    version: 1,
    createdAt: '2026-05-18T11:00:00Z',
    updatedAt: '2026-05-18T11:00:00Z',
  },
];

export const seedOfferLines: OfferLine[] = [
  {
    id: 1,
    offerId: 1,
    lp: 1,
    nazwaPrzyrzadu: 'Części do systemu klimatyzacji',
    ilosc: 1,
    sourceRfqId: 1,
    sourceBomNodeId: 5, // root of RFQ 1's BOM tree (Zespół klimatyzacji)
    kosztWykonania: 0,
    negocjacje: 0,
    cenaSprzedazy: 0,
  },
  {
    id: 2,
    offerId: 2,
    lp: 1,
    nazwaPrzyrzadu: 'Rury tytanowe',
    ilosc: 1,
    sourceRfqId: 2,
    sourceBomNodeId: null, // RFQ 2 has no BOM; the line is frozen anyway
    kosztWykonania: 2500,
    negocjacje: 0,
    cenaSprzedazy: 3000,
  },
];
